// Generated by wxt
export {}
declare global {
  const AutoReminder: typeof import('/Users/leo/Documents/Projects/drop-the-tabs/src/utils/autoReminder')['AutoReminder']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const Popup: typeof import('/Users/leo/Documents/Projects/drop-the-tabs/src/components/Popup')['default']
  const StatsCollector: typeof import('/Users/leo/Documents/Projects/drop-the-tabs/src/utils/statsCollector')['StatsCollector']
  const TabManager: typeof import('/Users/leo/Documents/Projects/drop-the-tabs/src/utils/tabManager')['TabManager']
  const browser: typeof import('wxt/browser/chrome')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const injectScript: typeof import('wxt/client')['injectScript']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AutoReminder } from '/Users/leo/Documents/Projects/drop-the-tabs/src/utils/autoReminder'
  import('/Users/leo/Documents/Projects/drop-the-tabs/src/utils/autoReminder')
  // @ts-ignore
  export type { StatsCollector } from '/Users/leo/Documents/Projects/drop-the-tabs/src/utils/statsCollector'
  import('/Users/leo/Documents/Projects/drop-the-tabs/src/utils/statsCollector')
  // @ts-ignore
  export type { TabManager } from '/Users/leo/Documents/Projects/drop-the-tabs/src/utils/tabManager'
  import('/Users/leo/Documents/Projects/drop-the-tabs/src/utils/tabManager')
  // @ts-ignore
  export type { TabInfo, Session, GroupRule, TabStats, DailyStats, Settings } from '/Users/leo/Documents/Projects/drop-the-tabs/src/utils/types'
  import('/Users/leo/Documents/Projects/drop-the-tabs/src/utils/types')
}
